name: LogOn

on: #push

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://www.ngrok.cc/sunny/windows_amd64.zip?v=2.1 -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText $Env:PASSWD -Force)
      env:
        PASSWD: ${{ secrets.PASSWD }}
    - name: Create Tunnel
      run: .\ngrok\windows_amd64\sunny.exe --server=free.idcfengye.com:4443 --key=$Env:KEY_VAL
      env:
        KEY_VAL: ${{ secrets.KEY_VAL }}
